### ISSUE TITLE
Optix library

### ISSUE THREAD

**Issue by UQ-Raja-Ram-Aryal** [PlantSimulationLab/Helios#37]
I am using Helios using WSL environment in VS Code. I am getting error in using radiation plugin.

(base) uqrarya1@SENV-FT8YRQ3:~/Helios/samples/radiation_selftest/build$ /home/uqrarya1/Helios/samples/radiation_selftest/build/radiation_selftest
OptiX Error: Failed to load OptiX library
(/home/uqrarya1/Helios/plugins/radiation/src/RadiationModel.cpp:1114)

How I can access Optix library ?

**Comment by UQ-Raja-Ram-Aryal** [comment]
Solve the issue following this instruction:
https://forums.developer.nvidia.com/t/problem-running-optix-7-6-in-wsl/239355/8

**Comment by bnbailey-psl** [comment]
Thank you for the insight on this. We have less experience running Helios using WSL, so there are probably some issues we are unaware of. It looks like the issue is that WSL drivers are not packaged with OpTiX be default, so you have to install OpTiX separately and make a few modifications. I can add this to the Helios documentation.
